//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KombajnPDF.Properties.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Polski {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Polski() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KombajnPDF.Properties.Translations.Strings.Polski", typeof(Strings_Polski).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz pliki.
        /// </summary>
        internal static string COMBINE_FILES {
            get {
                return ResourceManager.GetString("COMBINE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połączono pliki.
        /// </summary>
        internal static string COMBINED_FILES {
            get {
                return ResourceManager.GetString("COMBINED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencja zewnętrznych komponentów.
        /// </summary>
        internal static string EXTERNAL_COMPONENT_LICENSE {
            get {
                return ResourceManager.GetString("EXTERNAL_COMPONENT_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa pliku.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o aplikacji.
        /// </summary>
        internal static string INFORMATION_ABOUT_APPLICATION {
            get {
                return ResourceManager.GetString("INFORMATION_ABOUT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja „KombajnPDF” umożliwia nie tylko łączenie wielu plików PDF w jeden, ale także wybór konkretnych stron z każdego pliku PDF, które mają zostać wyodrębnione i dołączone do dokumentu wynikowego..
        /// </summary>
        internal static string INFORMATION_ABOUT_APPLICATION_TEXT {
            get {
                return ResourceManager.GetString("INFORMATION_ABOUT_APPLICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        internal static string INFORMATIONS {
            get {
                return ResourceManager.GetString("INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrukcja obsługi.
        /// </summary>
        internal static string INSTRUCTION_MANUAL {
            get {
                return ResourceManager.GetString("INSTRUCTION_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Po uruchomieniu aplikacji należy dodać pliki PDF, które chcemy połączyć – służy do tego przycisk z ikoną plusa.
        ///2. Dodane pliki pojawią się na liście, gdzie można zmieniać ich kolejność (przyciski z ikoną strzałki w dół i przyciski z ikoną strzałki w górę) lub usuwać wybrane pozycje przycisk z ikoną kosza na śmieci.
        ///3. Po ustawieniu odpowiedniej kolejności plików należy kliknąć przycisk połącz pliki, aby połączyć wybrane dokumenty w jeden plik PDF. 
        ///4. Program poprosi o wskazanie miejsca i nazwy dla n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INSTRUCTION_MANUAL_TEXT {
            get {
                return ResourceManager.GetString("INSTRUCTION_MANUAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język zmieniony.
        /// </summary>
        internal static string LANGUAGE_CHANGED {
            get {
                return ResourceManager.GetString("LANGUAGE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencja.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główna licencja.
        /// </summary>
        internal static string MAIN_LICENSE {
            get {
                return ResourceManager.GetString("MAIN_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka do pliku.
        /// </summary>
        internal static string PATH_TO_FILE {
            get {
                return ResourceManager.GetString("PATH_TO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablon.
        /// </summary>
        internal static string PATTERN {
            get {
                return ResourceManager.GetString("PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość stron.
        /// </summary>
        internal static string TOTAL_PAGES {
            get {
                return ResourceManager.GetString("TOTAL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred.
        /// </summary>
        internal static string UNEXPECTED_EXCEPTION_OCCURED {
            get {
                return ResourceManager.GetString("UNEXPECTED_EXCEPTION_OCCURED", resourceCulture);
            }
        }
    }
}
