//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KombajnPDF.App.Properties.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KombajnPDF.App.Properties.Translations.Strings.English", typeof(Strings_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine files.
        /// </summary>
        internal static string COMBINE_FILES {
            get {
                return ResourceManager.GetString("COMBINE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined files.
        /// </summary>
        internal static string COMBINED_FILES {
            get {
                return ResourceManager.GetString("COMBINED_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External component license.
        /// </summary>
        internal static string EXTERNAL_COMPONENT_LICENSE {
            get {
                return ResourceManager.GetString("EXTERNAL_COMPONENT_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the application.
        /// </summary>
        internal static string INFORMATION_ABOUT_APPLICATION {
            get {
                return ResourceManager.GetString("INFORMATION_ABOUT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;KombajnPDF&quot; application allows not only merging multiple PDF files into one, but also selecting specific pages from each PDF file to be extracted and included in the output document..
        /// </summary>
        internal static string INFORMATION_ABOUT_APPLICATION_TEXT {
            get {
                return ResourceManager.GetString("INFORMATION_ABOUT_APPLICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string INFORMATIONS {
            get {
                return ResourceManager.GetString("INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manual.
        /// </summary>
        internal static string INSTRUCTION_MANUAL {
            get {
                return ResourceManager.GetString("INSTRUCTION_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. After launching the application, add the PDF files you want to merge – use the button with the plus icon.
        ///2. The added files will appear in the list, where you can change their order (buttons with up and down arrow icons) or remove selected items (button with the trash icon).
        ///3. After setting the correct order of files, click the combine files button to merge the selected documents into one PDF file.
        ///4. The program will ask you to specify the location and name for the new file.
        ///
        ///How to select pages to ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INSTRUCTION_MANUAL_TEXT {
            get {
                return ResourceManager.GetString("INSTRUCTION_MANUAL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed.
        /// </summary>
        internal static string LANGUAGE_CHANGED {
            get {
                return ResourceManager.GetString("LANGUAGE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main license.
        /// </summary>
        internal static string MAIN_LICENSE {
            get {
                return ResourceManager.GetString("MAIN_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to file.
        /// </summary>
        internal static string PATH_TO_FILE {
            get {
                return ResourceManager.GetString("PATH_TO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        internal static string PATTERN {
            get {
                return ResourceManager.GetString("PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages count.
        /// </summary>
        internal static string TOTAL_PAGES {
            get {
                return ResourceManager.GetString("TOTAL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred.
        /// </summary>
        internal static string UNEXPECTED_EXCEPTION_OCCURED {
            get {
                return ResourceManager.GetString("UNEXPECTED_EXCEPTION_OCCURED", resourceCulture);
            }
        }
    }
}
